config/routes.rb
Mybookings::Engine.routes.draw do

  devise_for :users,
    class_name: 'Mybookings::User',
    controllers: { sessions: 'mybookings/sessions', omniauth_callbacks: 'mybookings/omniauth_callbacks' },
    module: :devise

  root 'application#index'

  resources :bookings, only: [:index, :show, :create, :update, :destroy] do
    resources :events do
      get :edit_feedback
      put :set_feedback
    end
  end

  resources :events, only: [:index]

  resources :resource_types do
    get 'bookings/new', to: 'bookings#new'
    post 'bookings', to: 'bookings#create'
  end

  resources :resources do
    get :events
  end

  namespace :backend do

    resources :resources do
      put :switch_availability
      resources :events do
        get :delete_confirmation
      end
    end

    resources :resource_types do
      get :use_by_resource, on: :member
      get :use_by_hour, on: :member
    end

    resources :users

    resources :bookings do
      resources :events, only: [:index]
    end

    resources :statistics, only: [:index]

    get 'statistics/by_resource', to: 'statistics#by_resource'
    get 'statistics/by_hour', to: 'statistics#by_hour'

  end

end

app/controllers/admin/resource_types_controller.rb
class Admin::ResourceTypesController < Admin::BaseController

  def index
    @resource_types = ResourceType.all
  end

  def new
    @resource_type = ResourceType.new
  end

  def create
    @resource_type = ResourceType.new(resource_type_params)
    return render 'new' unless @resource_type.valid?
    @resource_type.save!
    return redirect_to admin_resource_types_path
  end

  private

  def resource_type_params
    params.require(:resource_type).permit!
  end

end

app/controllers/concerns/mybookings/backend/administerable.rb
module Mybookings
  module Backend::Administerable
    extend ActiveSupport::Concern

    included do
      before_action :authorize_if_admin
    end

    private

    def authorize_if_admin
      @authorized = true if current_user.has_role? :admin
    end
  end
end

app/controllers/concerns/mybookings/backend/authorizable.rb
module Mybookings
  module Backend::Authorizable
    extend ActiveSupport::Concern

    included do
      before_action :authorize!
    end

    private

    def authorize!
      redirect_to (request.referrer || root_path), alert: t('not_authorized') unless @authorized
    end
  end
end

app/controllers/concerns/mybookings/backend/manageable.rb
module Mybookings
  module Backend::Manageable
    extend ActiveSupport::Concern

    included do
      before_action :authorize_if_manager
    end

    private

    def authorize_if_manager
      @authorized = true if current_user.has_role? :manager
    end
  end
end

app/controllers/mybookings/backend/base_controller.rb
module Mybookings
  class Backend::BaseController < ApplicationController
    include Pundit

    before_action :authenticate_user!
    before_action :load_current_user

    layout 'layouts/mybookings/backend'

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def load_current_user
      @current_user = current_user
    end

    def user_not_authorized
      redirect_to (request.referrer || root_path), alert: t('not_authorized')
    end
  end
end

app/controllers/mybookings/backend/bookings_controller.rb
module Mybookings
  class Backend::BookingsController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_booking, only: [:show]

    def show; end

    private

    def load_booking
      @booking = Booking.find(params[:id]).decorate
    end

  end
end

app/controllers/mybookings/backend/events_controller.rb
module Mybookings
  class Backend::EventsController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_resource, only: [:index, :delete_confirmation, :destroy, :update]
    before_action :load_event, only: [:delete_confirmation, :destroy, :update]

    def index
      @events = @resource.events
    end

    def delete_confirmation
      @delete_form = DeleteEventForm.new
      @resources = @event.alternative_resources
    end

    def destroy
      @delete_form = DeleteEventForm.new(params[:delete_event_form])

      unless @delete_form.valid?
        @resources = @event.alternative_resources
        return render 'delete_confirmation'
      end

      booking = @event.booking

      @event.destroy!
      booking.destroy! unless booking.has_events?

      logger.info "The event #{@event.id} of the booking #{@event.booking.id} in the resource #{@resource.name} has been deleted. The reason is: #{@delete_form.reason}"

      redirect_to backend_resource_events_path, notice: I18n.t('mybookings.backend.events.destroy.cancel_notice')
    end

    def update
      return render 'delete_confirmation' unless @event.valid?

      @event.update(event_params)
      redirect_to backend_resources_path, notice: I18n.t('mybookings.backend.events.update.reallocated_notice')
    end

    private

    def event_params
      params.require(:event).permit(:resource_id)
    end

    def load_event
      event_id = params[:id] || params[:event_id]

      @event = Event.find(event_id)
      authorize @event
    end

    def load_resource
      resource_id = params[:resource_id] || params[:id]

      @resource = Resource.find(resource_id)
      authorize @resource, :manage_by_manager?
    end

  end
end

app/controllers/mybookings/backend/resource_types_controller.rb
module Mybookings
  class Backend::ResourceTypesController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_resource_type, only: [:edit, :update, :destroy, :use_by_resource, :use_by_hour]
    before_action :load_valid_roles, only: [:new, :edit, :create, :update]
    before_action :preprocess_notifications_emails_list, only: [:create, :update]

    def index
      @resource_types = ResourceType.all
    end

    def new
      @resource_type = ResourceType.new
    end

    def create
      @resource_type = ResourceType.new(resource_type_params)
      return render 'new' unless @resource_type.valid?
      @resource_type.save!
      return redirect_to backend_resource_types_path
    end

    def edit; end

    def update
      return render 'edit' unless @resource_type.update_attributes(resource_type_params)
      return redirect_to backend_resource_types_path
    end

    def destroy
      @resource_type.destroy!
      redirect_to backend_resource_types_path
    end

    def use_by_resource
      @use = @resource_type.use_by_resource
    end

    def use_by_hour
      @chart = UseByHourPresenter.new(@resource_type.use_by_hour)
    end

    private

    def resource_type_params
      params.require(:resource_type).permit!
    end

    def load_resource_type
      resource_type_id = params[:id] || params[:resource_type_id]

      @resource_type = ResourceType.find(resource_type_id)
      authorize @resource_type
    end

    def load_valid_roles
      @valid_roles = ResourceType.valid_roles
    end

    def preprocess_notifications_emails_list
      emails_list = params[:resource_type][:notifications_emails]
      emails_list = emails_list.split(',').map { |e| e.gsub(/\s+/, '') }
      params[:resource_type][:notifications_emails] = emails_list
    end
  end
end

app/controllers/mybookings/backend/resources_controller.rb
module Mybookings
  class Backend::ResourcesController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_resource, only: [:edit, :update, :switch_availability, :destroy]

    def index
      @resources = policy_scope(Resource).by_id
    end

    def switch_availability
      @resource.switch_availability!
      return redirect_to backend_resources_path
    end

    def new
      @resource = Resource.new
      load_current_user_managed_resource_types
    end

    def create
      @resource = Resource.new(resource_params)
      authorize @resource, :manage_by_manager?

      return redirect_to backend_resources_path if @resource.save

      load_current_user_managed_resource_types
      render 'new'
    end

    def edit; end

    def update
      return render 'edit' unless @resource.update_attributes(resource_params)
      redirect_to backend_resources_path
    end

    def destroy
      @resource.destroy!
      redirect_to backend_resources_path
    end

    private

    def resource_params
      params.require(:resource).permit!
    end

    def load_resource
      resource_id = params[:id] || params[:resource_id]

      @resource = Resource.find(resource_id)
      authorize @resource, :manage_by_manager?
    end

    def load_current_user_managed_resource_types
      @managed_resource_types = ResourceTypePolicy::Scope.new(current_user, ResourceType).resolve_for_managers
    end
  end
end

app/controllers/mybookings/backend/statistics_controller.rb
module Mybookings
  class Backend::StatisticsController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_current_user_managed_resource_types, only: [:by_resource, :by_hour]

    def index; end

    def by_resource
      @statistics_form = StatisticsForm.new({ resource_type_id: @resource_types.first.id })
    end

    def by_hour
      @statistics_form = StatisticsForm.new({ resource_type_id: @resource_types.first.id })
    end

    private

    def load_current_user_managed_resource_types
      @resource_types = ResourceTypePolicy::Scope.new(current_user, ResourceType).resolve_for_managers
    end
  end
end

app/controllers/mybookings/backend/users_controller.rb
module Mybookings
  class Backend::UsersController < Backend::BaseController
    include Backend::Administerable
    include Backend::Authorizable

    before_action :load_user, only: [:edit, :update]
    before_action :load_valid_roles, only: [:new, :edit]
    before_action :load_resource_types, only: [:new, :edit]

    def index
      if params[:search].nil?
        @users = policy_scope(User).by_id.page(params[:page])
      else
        @users = policy_scope(User).search(params[:search]).by_id.page(params[:page])
      end
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.password = Devise.friendly_token.first(8)

      if @user.valid?
        @user.save!
        return redirect_to backend_users_path
      end

      load_valid_roles
      load_resource_types
      render 'new'
    end

    def edit; end

    def update
      return redirect_to backend_users_path if @user.update(user_params)
      load_valid_roles
      load_resource_types
      render 'edit'
    end

    private

    def load_user
      user_id = params[:id] || params[:user_id]

      @user = User.find(user_id)
      authorize @user
    end

    def load_valid_roles
      @valid_roles = User.valid_roles
    end

    def load_resource_types
      @resource_types = ResourceTypePolicy::Scope.new(current_user, ResourceType).resolve_for_managers.by_name
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :roles => [], :resource_type_ids => [])
    end
  end
end

app/helpers/mybookings/backend_helper.rb
module Mybookings
  module BackendHelper
    def active_class_for controller
      'active' if params[:controller] == controller
    end

    def resource_tr_class resource
      'danger' if resource.disabled?
    end

    def bookings_counters_for resource
      expired_bookings = resource.expired_bookings_count
      expired = t('.expired', expired_bookings: expired_bookings)
      expired_formatted = "<span class='label label-#{bootstrap_class_for('expired')}'>#{expired}</span>"

      pending_bookings = resource.pending_bookings_count
      pending = t('.pending', pending_bookings: pending_bookings) if pending_bookings > 0
      pending_formatted = "<span class='label label-#{bootstrap_class_for('pending')}'>#{pending}</span>"

      occurring_bookings = resource.occurring_bookings_count
      occurring = t('.occurring', occurring_bookings: occurring_bookings) if occurring_bookings > 0
      occurring_formatted = "<span class='label label-#{bootstrap_class_for('occurring')}'>#{occurring}</span>"

      "#{expired_formatted} #{pending_formatted} #{occurring_formatted}".html_safe
    end

    def roles_for user
      user.role_symbols.join(", ")
    end

    def available_resource_types_extensions
      extensions = ResourceTypesExtensions.constants
      extensions.delete(:BaseExtension)

      extensions
    end
  end
end

app/views/mybookings/backend/resource_types/_form_fields.html.haml
= render_model_base_errors f.object

.panel.panel-default
  .panel-heading
    = t('.basic_information')
  .panel-body
    = f.input :name
    = f.input :extension, as: :select, collection: available_resource_types_extensions, include_blank: false, default: 'DefaultExtension'

.panel.panel-default
  .panel-heading
    = t('.options')
  .panel-body
    = f.input :notifications_email_from, hint: t('mybookings.backend.resource_types.hints.notifications_email_from'), placeholder: t('mybookings.backend.resource_types.placeholders.notifications_email_from')
    = f.input :notifications_emails, hint: t('mybookings.backend.resource_types.hints.notifications_emails'), placeholder: t('mybookings.backend.resource_types.placeholders.notifications_emails'), input_html: { value: @resource_type.notifications_emails.join(', ') }
    .row
      .col-xs-12.col-sm-4
        = f.input :minutes_in_advance, min_max: true, hint: t('mybookings.backend.resource_types.hints.minutes_in_advance')
      .col-xs-12.col-sm-4
        = f.input :minutes_of_grace, min_max: true, hint: t('mybookings.backend.resource_types.hints.minutes_of_grace')
    .row
      .col-xs-12.col-sm-4
        = f.input :limit_hours_duration, min_max: true, hint: t('mybookings.backend.resource_types.hints.limit_hours_duration')
      .col-xs-12.col-sm-4
        = f.input :limit_days_for_recurring_events, min_max: true, hint: t('mybookings.backend.resource_types.hints.limit_days_for_recurring_events')
      .col-xs-12.col-sm-4
        = f.input :limit_days_for_feedback, min_max: true, hint: t('mybookings.backend.resource_types.hints.limit_days_for_feedback')
      .col-xs-12
        = f.input :hide_comment_field, hint: t('mybookings.backend.resource_types.hints.hide_comment_field')

.panel.panel-default
  .panel-heading
    = t('.roles')
  .panel-body
    = f.input :roles, as: :check_boxes, collection: @valid_roles, checked: @resource_type.roles, label: false

app/views/mybookings/backend/resource_types/_resource_type.html.haml
%tr
  %td= resource_type.id
  %td= link_to resource_type.name, edit_backend_resource_type_path(resource_type)
  %td= resource_type.resources_number
  %td
    = link_to icon_with_text('pencil', t('.edit')), edit_backend_resource_type_path(resource_type), class: 'btn btn-default btn-xs'
    = link_to_delete t('.delete'), backend_resource_type_path(resource_type), t('.delete_confirmation'), class: 'btn btn-default btn-xs'

app/views/mybookings/backend/resource_types/edit.html.haml
= title

= simple_form_for @resource_type, url: backend_resource_type_path(@resource_type) do |f|
  = render partial: 'form_fields', locals: { f: f }
  = f.button icon_with_text('ok', t('.update_resource_type')), class: 'btn btn-primary'

app/views/mybookings/backend/resource_types/index.html.haml
= title

- if @resource_types.any?
  = table_for @resource_types, 'mybookings/backend/resource_types/resource_type', ['resource_type.id', 'resource_type.name', 'resource_type.resources_number'], 'table-resources-type'

  = content_for :actions do
    = link_to icon_with_text('plus', t('.new_resource_type')), new_backend_resource_type_path, class: 'btn btn-primary'

- else
  .lead
    %p= t('.no_resource_types')
    %p= link_to icon_with_text('plus', t('.new_resource_type')), new_backend_resource_type_path, class: 'btn btn-primary'

app/views/mybookings/backend/resource_types/new.html.haml
= title

= simple_form_for @resource_type, url: backend_resource_types_path do |f|
  = render partial: 'form_fields', locals: { f: f }
  = f.button icon_with_text('ok', t('.create_resource_type')), class: 'btn btn-primary'