config/routes.rb
Mybookings::Engine.routes.draw do

  devise_for :users,
    class_name: 'Mybookings::User',
    controllers: { sessions: 'mybookings/sessions', omniauth_callbacks: 'mybookings/omniauth_callbacks' },
    module: :devise

  root 'application#index'

  resources :bookings, only: [:index, :show, :create, :update, :destroy] do
    resources :events do
      get :edit_feedback
      put :set_feedback
    end
  end

  resources :events, only: [:index]

  resources :resource_types do
    get 'bookings/new', to: 'bookings#new'
    post 'bookings', to: 'bookings#create'
  end

  resources :resources do
    get :events
  end

  namespace :backend do

    resources :resources do
      put :switch_availability
      resources :events do
        get :delete_confirmation
      end
    end

    resources :resource_types do
      get :use_by_resource, on: :member
      get :use_by_hour, on: :member
    end

    resources :users

    resources :bookings do
      resources :events, only: [:index]
    end

    resources :statistics, only: [:index]

    get 'statistics/by_resource', to: 'statistics#by_resource'
    get 'statistics/by_hour', to: 'statistics#by_hour'

  end

end

app/models/concerns/mybookings/loggable.rb
module Mybookings
  module Loggable
    extend ActiveSupport::Concern

    included do
      after_create :notify_record_created
      after_update :notify_record_updated

      def log_for_record_created name, datetime
        Rails.logger.info "#{name} - New #{self.class.name} (#{self.id}) at #{datetime}."
      end

      def log_for_record_updated name, datetime
        Rails.logger.info "#{name} - #{self.class.name} (#{self.id}) updated at #{datetime}."
      end
    end

    private

    def notify_record_created
      ActiveSupport::Notifications.instrument('mybookings_info.record_created', object: self)
    end

    def notify_record_updated
      ActiveSupport::Notifications.instrument('mybookings_info.record_updated', object: self)
    end
  end
end

app/models/mybookings/application_record.rb
module Mybookings
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/mybookings/resource.rb
module Mybookings
  class Resource < ApplicationRecord
    include Loggable

    acts_as_paranoid

    belongs_to :resource_type
    has_many :events, dependent: :destroy

    validates :name, :resource_type, presence: true

    delegate :name, to: :resource_type, prefix: true
    delegate :extension, to: :resource_type, prefix: true
    delegate :managed_by?, to: :resource_type, prefix: true
    delegate :users, to: :resource_type, prefix: true

    def self.available_by_resource_type resource_type
      includes(:resource_type).order(Arel.sql('LENGTH(mybookings_resources.name)')).order('mybookings_resources.name asc').where(disabled: false, resource_type: resource_type)
    end

    def self.by_id
      order(id: :asc)
    end

    def switch_availability!
      self.update_attribute(:disabled, !self.disabled)
    end

    def bookings
      Booking.joins(:events).where(events: { resource: self })
    end

    def pending_bookings_count
      Booking.joins(:events).where(mybookings_events: { status: Event::statuses[:pending], resource_id: self }).count
    end

    def occurring_bookings_count
      Booking.joins(:events).where(mybookings_events: { status: Event::statuses[:occurring], resource_id: self }).count
    end

    def expired_bookings_count
      Booking.joins(:events).where(mybookings_events: { status: Event::statuses[:expired], resource_id: self }).count
    end

    def name_prefixed_with_resource_type
      "#{self.resource_type.name}: #{self.name}"
    end
  end
end

app/controllers/concerns/mybookings/backend/administerable.rb
module Mybookings
  module Backend::Administerable
    extend ActiveSupport::Concern

    included do
      before_action :authorize_if_admin
    end

    private

    def authorize_if_admin
      @authorized = true if current_user.has_role? :admin
    end
  end
end

app/controllers/concerns/mybookings/backend/authorizable.rb
module Mybookings
  module Backend::Authorizable
    extend ActiveSupport::Concern

    included do
      before_action :authorize!
    end

    private

    def authorize!
      redirect_to (request.referrer || root_path), alert: t('not_authorized') unless @authorized
    end
  end
end

app/controllers/concerns/mybookings/backend/manageable.rb
module Mybookings
  module Backend::Manageable
    extend ActiveSupport::Concern

    included do
      before_action :authorize_if_manager
    end

    private

    def authorize_if_manager
      @authorized = true if current_user.has_role? :manager
    end
  end
end

app/controllers/mybookings/application_controller.rb
module Mybookings
  class ApplicationController < ::ActionController::Base
    # TODO: That makes login with SAML crashes
    # protect_from_forgery with: :exception

    def index
      return redirect_to bookings_path if user_signed_in?
      return render 'homepage'
    end

    private

    def after_sign_in_path_for resource
      bookings_path
    end

    def after_sign_out_path_for resource
      root_path
    end
  end
end

app/controllers/mybookings/backend/base_controller.rb
module Mybookings
  class Backend::BaseController < ApplicationController
    include Pundit

    before_action :authenticate_user!
    before_action :load_current_user

    layout 'layouts/mybookings/backend'

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def load_current_user
      @current_user = current_user
    end

    def user_not_authorized
      redirect_to (request.referrer || root_path), alert: t('not_authorized')
    end
  end
end

app/controllers/mybookings/backend/bookings_controller.rb
module Mybookings
  class Backend::BookingsController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_booking, only: [:show]

    def show; end

    private

    def load_booking
      @booking = Booking.find(params[:id]).decorate
    end

  end
end

app/controllers/mybookings/backend/events_controller.rb
module Mybookings
  class Backend::EventsController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_resource, only: [:index, :delete_confirmation, :destroy, :update]
    before_action :load_event, only: [:delete_confirmation, :destroy, :update]

    def index
      @events = @resource.events
    end

    def delete_confirmation
      @delete_form = DeleteEventForm.new
      @resources = @event.alternative_resources
    end

    def destroy
      @delete_form = DeleteEventForm.new(params[:delete_event_form])

      unless @delete_form.valid?
        @resources = @event.alternative_resources
        return render 'delete_confirmation'
      end

      booking = @event.booking

      @event.destroy!
      booking.destroy! unless booking.has_events?

      logger.info "The event #{@event.id} of the booking #{@event.booking.id} in the resource #{@resource.name} has been deleted. The reason is: #{@delete_form.reason}"

      redirect_to backend_resource_events_path, notice: I18n.t('mybookings.backend.events.destroy.cancel_notice')
    end

    def update
      return render 'delete_confirmation' unless @event.valid?

      @event.update(event_params)
      redirect_to backend_resources_path, notice: I18n.t('mybookings.backend.events.update.reallocated_notice')
    end

    private

    def event_params
      params.require(:event).permit(:resource_id)
    end

    def load_event
      event_id = params[:id] || params[:event_id]

      @event = Event.find(event_id)
      authorize @event
    end

    def load_resource
      resource_id = params[:resource_id] || params[:id]

      @resource = Resource.find(resource_id)
      authorize @resource, :manage_by_manager?
    end

  end
end

app/controllers/mybookings/backend/resource_types_controller.rb
module Mybookings
  class Backend::ResourceTypesController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_resource_type, only: [:edit, :update, :destroy, :use_by_resource, :use_by_hour]
    before_action :load_valid_roles, only: [:new, :edit, :create, :update]
    before_action :preprocess_notifications_emails_list, only: [:create, :update]

    def index
      @resource_types = ResourceType.all
    end

    def new
      @resource_type = ResourceType.new
    end

    def create
      @resource_type = ResourceType.new(resource_type_params)
      return render 'new' unless @resource_type.valid?
      @resource_type.save!
      return redirect_to backend_resource_types_path
    end

    def edit; end

    def update
      return render 'edit' unless @resource_type.update_attributes(resource_type_params)
      return redirect_to backend_resource_types_path
    end

    def destroy
      @resource_type.destroy!
      redirect_to backend_resource_types_path
    end

    def use_by_resource
      @use = @resource_type.use_by_resource
    end

    def use_by_hour
      @chart = UseByHourPresenter.new(@resource_type.use_by_hour)
    end

    private

    def resource_type_params
      params.require(:resource_type).permit!
    end

    def load_resource_type
      resource_type_id = params[:id] || params[:resource_type_id]

      @resource_type = ResourceType.find(resource_type_id)
      authorize @resource_type
    end

    def load_valid_roles
      @valid_roles = ResourceType.valid_roles
    end

    def preprocess_notifications_emails_list
      emails_list = params[:resource_type][:notifications_emails]
      emails_list = emails_list.split(',').map { |e| e.gsub(/\s+/, '') }
      params[:resource_type][:notifications_emails] = emails_list
    end
  end
end

app/controllers/mybookings/backend/resources_controller.rb
module Mybookings
  class Backend::ResourcesController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_resource, only: [:edit, :update, :switch_availability, :destroy]

    def index
      @resources = policy_scope(Resource).by_id
    end

    def switch_availability
      @resource.switch_availability!
      return redirect_to backend_resources_path
    end

    def new
      @resource = Resource.new
      load_current_user_managed_resource_types
    end

    def create
      @resource = Resource.new(resource_params)
      authorize @resource, :manage_by_manager?

      return redirect_to backend_resources_path if @resource.save

      load_current_user_managed_resource_types
      render 'new'
    end

    def edit; end

    def update
      return render 'edit' unless @resource.update_attributes(resource_params)
      redirect_to backend_resources_path
    end

    def destroy
      @resource.destroy!
      redirect_to backend_resources_path
    end

    private

    def resource_params
      params.require(:resource).permit!
    end

    def load_resource
      resource_id = params[:id] || params[:resource_id]

      @resource = Resource.find(resource_id)
      authorize @resource, :manage_by_manager?
    end

    def load_current_user_managed_resource_types
      @managed_resource_types = ResourceTypePolicy::Scope.new(current_user, ResourceType).resolve_for_managers
    end
  end
end

app/controllers/mybookings/backend/statistics_controller.rb
module Mybookings
  class Backend::StatisticsController < Backend::BaseController
    include Backend::Administerable
    include Backend::Manageable
    include Backend::Authorizable

    before_action :load_current_user_managed_resource_types, only: [:by_resource, :by_hour]

    def index; end

    def by_resource
      @statistics_form = StatisticsForm.new({ resource_type_id: @resource_types.first.id })
    end

    def by_hour
      @statistics_form = StatisticsForm.new({ resource_type_id: @resource_types.first.id })
    end

    private

    def load_current_user_managed_resource_types
      @resource_types = ResourceTypePolicy::Scope.new(current_user, ResourceType).resolve_for_managers
    end
  end
end

app/controllers/mybookings/backend/users_controller.rb
module Mybookings
  class Backend::UsersController < Backend::BaseController
    include Backend::Administerable
    include Backend::Authorizable

    before_action :load_user, only: [:edit, :update]
    before_action :load_valid_roles, only: [:new, :edit]
    before_action :load_resource_types, only: [:new, :edit]

    def index
      if params[:search].nil?
        @users = policy_scope(User).by_id.page(params[:page])
      else
        @users = policy_scope(User).search(params[:search]).by_id.page(params[:page])
      end
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      @user.password = Devise.friendly_token.first(8)

      if @user.valid?
        @user.save!
        return redirect_to backend_users_path
      end

      load_valid_roles
      load_resource_types
      render 'new'
    end

    def edit; end

    def update
      return redirect_to backend_users_path if @user.update(user_params)
      load_valid_roles
      load_resource_types
      render 'edit'
    end

    private

    def load_user
      user_id = params[:id] || params[:user_id]

      @user = User.find(user_id)
      authorize @user
    end

    def load_valid_roles
      @valid_roles = User.valid_roles
    end

    def load_resource_types
      @resource_types = ResourceTypePolicy::Scope.new(current_user, ResourceType).resolve_for_managers.by_name
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :roles => [], :resource_type_ids => [])
    end
  end
end

app/controllers/mybookings/base_controller.rb
module Mybookings
  class BaseController < ApplicationController
    include Pundit

    before_action :authenticate_user!
    before_action :load_current_user

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def load_current_user
      @current_user = current_user
    end

    def user_not_authorized
      redirect_to (request.referrer || root_path), alert: t('not_authorized')
    end
  end
end

app/controllers/mybookings/bookings_controller.rb
module Mybookings
  class BookingsController < BaseController
    before_action :load_booking, only: [:show, :update, :destroy]
    before_action :load_resource_type, only: [:new, :create]

    def index
      @resource_types = policy_scope(ResourceType.all)
      load_current_user_bookings
    end

    def new
      load_available_resources_by_resource_type @resource_type
      @booking = booking_type.new(resource_type: @resource_type)
    end

    def show; end

    def create
      @booking = booking_type.new_for_user(current_user, booking_params, event_type.to_s)

      if @booking.invalid?
        @resource_type = @booking.resource_type
        load_available_resources_by_resource_type @resource_type
        return render 'new'
      end

      @booking.save!
      @booking.confirm!

      redirect_to bookings_path
    end

    def update
      unless @booking.has_pending_events?
        flash.now[:alert] = I18n.t('mybookings.bookings.update.pending_events_required')
        return render 'show'
      end

      params = booking_params_for_update.merge({ prepared: false })
      if @booking.update_attributes(params)
        return redirect_to bookings_path
      end

      return render 'show'
    end

    def destroy
      # Only we delete the pending events associated to the booking.
      # If a booking has events with other statuses we don't delete the booking.
      if @booking.has_pending_events?
        @booking.delete_pending_events
      end

      unless @booking.has_events?
        @booking.cancel!
        @booking.destroy!
      end

      redirect_to bookings_path
    end

    private

    def booking_params
      params.require(booking_type.model_name.param_key).permit!
    end

    def booking_params_for_update
      {}
    end

    def booking_type
      Booking
    end

    def event_type
      Event
    end

    def booking_decorator_type
      BookingDecorator
    end

    def load_available_resources_by_resource_type resource_type
      @resources = Resource.available_by_resource_type resource_type
    end

    def load_booking
      @booking = booking_decorator_type.find(params[:id] || params[:booking_id]).decorate
      authorize @booking
    end

    def load_resource_type
      @resource_type = ResourceType.find(params[:resource_type_id])
    end

    def load_current_user_bookings
      # This map is necessary to decorate bookings in the array returned by the model method.
      # The model method not return a collection.
      @bookings = policy_scope(Booking).by_start_date_group_by_resource_type.map { |resource_type, bookings| [
        resource_type,
        booking_decorator_type.decorate_collection(bookings)
      ] }
    end
  end
end

app/views/mybookings/bookings/_resource_type_extension_defaultextension.html.haml
/ Nothing to do here…

app/views/mybookings/bookings/_resource_type_extension_defaultextension_edit.html.haml
/ Nothing to do here…

app/views/mybookings/bookings/_resource_type_extension_defaultextension_new.html.haml
/ Nothing to do here…

app/views/mybookings/bookings/index.html.haml
= title

= content_for :actions do
  .btn-group
    %button.btn.btn-primary.dropdown-toggle{ data: { toggle: 'dropdown' } }
      = t('.new_booking')
      %span.caret
    %ul.dropdown-menu
      - @resource_types.each do |resource_type|
        %li= link_to resource_type.name, resource_type_bookings_new_path(resource_type)

#bookings-calendar

:coffeescript
  Mybookings.BookingsCalendar.render('#bookings-calendar', "#{events_path}", "#{I18n.locale}")

app/views/mybookings/bookings/new.html.haml
- if @resource_type.nil?
  = title
- else
  = title t('.title_with_resource_type_name', resource_type_name: @resource_type.name)

.row
  .col-xs-12.col-sm-6
    = simple_form_for [@resource_type, @booking],
        url: resource_type_bookings_path(@resource_type, @booking),
        data: { behavior: 'dynamic-form' } do |f|

      = render_model_base_errors f.object

      .panel.panel-default
        .panel-body

          = f.input :resource_type_id, as: :hidden
          = f.association :proposed_resource, collection: @resources, include_blank: false, label_method: :name_prefixed_with_resource_type, input_html: { class: 'js-booking-resource-id' }

          .row
            .col-xs-12.col-sm-6
              = f.input :start_date, as: :datetimepicker, input_html: { class: 'js-booking-start-date' }
            .col-xs-12.col-sm-6
              = f.input :end_date, as: :datetimepicker, input_html: { class: 'js-booking-end-date' }

          .row
            .col-xs-12.col-sm-6
              = f.input :recurrent_type,
                  collection: recurrent_types_list,
                  as: :select,
                  include_blank: t('mybookings.bookings.recurrent_types.no_repeat'),
                  selected: '',
                  hint: t('mybookings.bookings.hints.recurring_hint'),
                  input_html: { class: 'js-booking-recurring-type' }
            .col-xs-12.col-sm-6.js-dynamic-form-element-to-hide
              -# The value '#booking_recurrent_type=""' does not work because it isn't
              -# an empty value. It is a string with two double quotes.
              = f.input :until_date,
                  as: :datetimepicker,
                  hint: t('mybookings.bookings.hints.until_date_hint'),
                  input_html: { data: { 'dynamic-form-disables-with': '.js-booking-recurring-type=' } }

          - if @booking.can_display_comment_field?
            = f.input :comment, as: :text, input_html: { rows: 3 }, hint: t('mybookings.bookings.hints.comment_hint')

      = render partial: "resource_type_extension_#{@booking.resource_type_extension.downcase}_new", locals: { form: f }

      = f.button icon_with_text('ok', t('.create_booking')), class: 'btn btn-primary'

  .col-xs-12.col-sm-6
    .panel.panel-default
      .panel-body
        %h4= t('.calendar_title')
        %p= t('.calendar_description')
        %hr
        #calendar

:coffeescript
  Mybookings.AvailabilityCalendar.render('#calendar', '.js-booking-resource-id', '.js-booking-start-date', '.js-booking-end-date', "#{I18n.locale.to_s}")

app/views/mybookings/bookings/new_booking_events_step.html.haml
= title t('.title', type_name: @resource_type.name)

.row
  .col-xs-12.col-sm-4
    = simple_form_for @booking, url: bookings_path, method: :post do |f|
      = render_model_base_errors f.object

      = f.input :resource_type_id, as: :hidden
      = f.input :resource_id, collection: @resources, include_blank: false, label_method: :name_prefixed_with_resource_type
      = f.input :start_date, as: :datetimepicker
      = f.input :end_date, as: :datetimepicker
      = f.input :recurrent_type, collection: recurrent_types_list, as: :radio_buttons, hint: t('.recurring_hint')
      = f.input :until_date, as: :datetimepicker
      = f.input :comment, as: :text, input_html: { rows: 5 }, hint: t('.comment_hint')
      = f.button icon_with_text('ok', t('.create_booking')), class: 'btn btn-primary'

  .col-xs-12.col-sm-8
    #calendar

:javascript
  $(document).ready(function() {
    var calendar = new Calendar('#calendar', '#booking_resource_id', '#{I18n.locale.to_s}')
  });

app/views/mybookings/bookings/see_more.js.haml
$("#booking-#{@booking.id} .events").html("#{ j render @events }")
$("#booking-#{@booking.id} .more-link").remove()

app/views/mybookings/bookings/show.haml
= title(t('.title', booking_id: @booking.id))

.row
  .col-xs-12
    .well
      .row
        .col-xs-12.col-sm-3
          %h4= t('.resource_type')
          %p= @booking.resource_type_name

        .col-xs-12.col-sm-3
          %h4= t('.creation_date')
          %p= l(@booking.created_at, format: :long)

        - if @booking.can_display_comment_field?
          .col-xs-12.col-sm-6
            %h4= t('.comment')
            - unless @booking.comment.blank?
              %p= @booking.comment
            - else
              %p
                %em= t('.no_comments')

      %hr

      %h4= t('.events')
      .row
        .booking-events
          - @booking.latest_events(4).each do |event|
            = render event

        - if @booking.events_count_greater_than?(4)
          .col-xs-12
            = link_to t('.load_all_events'), booking_events_path(@booking), class: 'link-show-all-events', remote: true

  .col-xs-12
    = simple_form_for @booking, url: booking_path(@booking) do |f|
      = render partial: "resource_type_extension_#{@booking.resource_type_extension.downcase}_edit", locals: { form: f }
      = f.button icon_with_text('ok', t('.update_booking')), class: 'btn btn-primary'

  - if @booking.has_pending_events?
    .col-xs-12
      %hr
      %h4= t('.cancel_booking')
      %p= t('.cancel_booking_description')
      = link_to_delete t('.cancel_booking'), booking_path(@booking), t('mybookings.delete_confirmation'), class: 'btn btn-default'